[package]
name = "t3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daemonize = "0.5.0"
notify-rust = "4.9.0"
serde_json = "1.0.107"
sgp4 = "1.2.2"
ureq = "2.8.0"
